### ISSUE TITLE
Missing types for `passport-google-openidconnect`

### ISSUE THREAD

**Issue by supercairos** [jaredhanson/passport-google-openidconnect#2]
Missing types for this library

**Comment by jaredhanson** [comment]
Types are typically provided by external parties, such as [DefinatelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).  It's not a current priority of this project to maintain typings for a language the project isn't written in.

**Comment by nathanhleung** [comment]
I wrote some type definitions  last month and added them to DefinitelyTyped; they should be available on npm now.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/74314
https://www.npmjs.com/package/@types/passport-google-oidc
