### ISSUE TITLE
types for  'passport-google-oidc'

### ISSUE THREAD

**Issue by 0x524c** [jaredhanson/passport-google-openidconnect#3]
Hello, congratulations on the passport project.

I'm testing the example 'todos-express-google' and currently converting everything to typescript. I would like to know if there are types of 'passport-google-oidc' in some repository.

Thanks!

**Comment by jaredhanson** [comment]
Not that I know of.  Most types in the Passport ecosystem are maintained by external parties.  Types for many strategies are available from [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

If you can't find any, it would be great if you could make them.  Thanks!

**Comment by 0x524c** [comment]
Ok, thanks!

**Comment by IronCrystal** [comment]
@524c Were types ever created for this project?

**Comment by 0x524c** [comment]
> @524c Were types ever created for this project?

I'm using another solution, authjs.

**Comment by nathanhleung** [comment]
@IronCrystal @0x524c I wrote some type definitions last month and added them to DefinitelyTyped; they should be available on npm now.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/74314
https://www.npmjs.com/package/@types/passport-google-oidc
